---
title: "Stat340_Final"
author: "Matthew Chiang, Ishaan Backliwal, Jordan Livingston, Eric Dietze, Vu Pham"
date: "11/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, include=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
# install.packages("cowplot")
library(cowplot)
```


# Loading Data

```{r loading data, include=FALSE}
astros_home <- read.csv("./data/astros_2017_player_splits_home.csv") %>%
  mutate(Name = str_split_fixed(Name, "\\\\", 2)[,1]) %>%
  mutate(split = "HOME")

astros_away <- read.csv("./data/astros_2017_player_splits_away.csv")%>%
  mutate(Name = str_split_fixed(Name, "\\\\", 2)[,1]) %>%
  mutate(split = "AWAY")

astros_2017 <- rbind(astros_home[-length(astros_home[,1]),], astros_away[-length(astros_away[,1]),]) %>% 
  drop_na()
```

### Astros 2017 Home Data

```{r, echo=FALSE}
head(astros_home)
```

### Astros 2017 Away Data

```{r, echo=FALSE}
head(astros_away)
```

# Preliminary Graphs - Home vs. Away

### comparing specific variables
```{r}
ops <- astros_2017 %>%
  drop_na() %>%
  ggplot() +
    geom_boxplot(aes(x=OPS, fill=split)) + 
    theme(legend.position = "none")
runs <- astros_2017 %>%
  drop_na() %>%
  ggplot() +
    geom_boxplot(aes(x=R, fill=split)) + 
    theme(legend.position = "none")
hits <- astros_2017 %>%
  drop_na() %>%
  ggplot() +
    geom_boxplot(aes(x=H, fill=split)) + 
    theme(legend.position = "none")
batting_avg <- astros_2017 %>%
  drop_na() %>%
  ggplot() +
    geom_boxplot(aes(x=BA, fill=split)) + 
    theme(legend.position = "none")
home_run <- astros_2017 %>%
  drop_na() %>%
  ggplot() +
    geom_boxplot(aes(x=HR, fill=split)) + 
    theme(legend.position = "none")
rbi <- astros_2017 %>%
  drop_na() %>%
  ggplot() +
    geom_boxplot(aes(x=RBI, fill=split))

plot_grid(ops, runs, hits, batting_avg, home_run, rbi, ncol=2)
```
```{r mc_runs, echo=FALSE}
runs_simulation <- function(n1, n2, avg){
  home_runs <- mean(rpois(n1, avg))
  away_runs <- mean(rpois(n2, avg))
  return(away_runs - home_runs)
}

runs_mc <- function(n1, n2, avg, reps = 1000){
  mean_differences <- rep(NA, reps)
  for(i in 1:reps){
     difference <- runs_simulation(n1, n2, avg)
     mean_differences[i] <- difference
  }
  return(mean_differences)
}

run_data <- astros_2017 %>%
  drop_na() %>%
  select(R, split)
player_run_avg <- mean(run_data$R)
num_home <- count(filter(run_data, split=="HOME"))$n
num_away <- count(filter(run_data, split=="AWAY"))$n

runs_sim <- runs_mc(num_home, num_away, player_run_avg)
home_away_runs_difference <- mean(filter(run_data, split=="HOME")$R)-mean(filter(run_data, split=="AWAY")$R)
runs_ci <- quantile(as.vector(runs_sim), prob=c(0.025, 0.975))

data.frame(diff = runs_sim)%>%
  ggplot() +
  geom_histogram(aes(x=diff), bins = 30) +
  geom_vline(aes(xintercept = home_away_runs_difference, color="Observed Difference"),lwd= 1) +
  geom_vline(aes(xintercept = c(runs_ci[1]), color="Confidence Interval"),lwd= 1) +
  geom_vline(aes(xintercept = c(runs_ci[2]),color="Confidence Interval"),lwd= 1) +
  scale_color_manual(
    name = "Legend", 
    values = c("Confidence Interval" = "#34c4cc", "Observed Difference" = "#ec8274")) +
  xlab("Difference of Averages") +
  ylab("Frequency") +
  ggtitle("Difference of Average Player Runs", subtitle = "Home vs. Away - Astros 2017")

```



